service:
  flush: 1
  daemon: off
  log_level: debug
  http_server: on
  http_listen: 127.0.0.1
  http_port: 23193
  hot_reload: on

includes:
  - private/*
  - pipeline/inputs/*
  - pipeline/filters/*
  - pipeline/outputs/*
